[tool.black]
# PEP 8 maximum line length
line-length = 79
# Minimum supported Python version
target-version = ['py37']
# Ignore the dku_config package because it was copied verbatim from
# dss-plugin-dkulib
extend-exclude = '/(python-lib/dku_config)/'
